KEYWORDS = [
    "python", "java", "javascript", "ruby", "php", "swift", 
    "kotlin", "go", "rust", "typescript", "perl", "matlab", "sql", 
    "html", "css", "scala", "dart", "shell", "lua", "haskell", 
    "fortran", "cobol", "ada", "erlang", "elixir", "groovy", 
    "prolog", "lisp", "scheme", "julia", "assembly", "tcl", "sas", "abap", "apex", 
    "scratch", "delphi", "vbscript", "smalltalk", "pascal", 
    "awk", "clojure", "postscript", "forth", 
    "crystal", "ocaml", "nim", "zig", "apl", "racket", "hack", "pike", "sed", 
    "git", "docker", "kubernetes", "jenkins", "ansible", "terraform", "apache", 
    "nginx", "mysql", "postgresql", "mongodb", "redis", "elasticsearch", 
    "tensorflow", "pytorch", "pandas", "numpy", "matplotlib", 
    "react", "angular", "flask", "django", "spring", 
    "express", "fastapi", "aws", "azure", "google cloud", "openstack", "graphql", 
    "rabbitmq", "kafka", "prometheus", "grafana", 
    "hadoop", "spark", "hive", "opencv", "opengl", "webassembly", "webrtc", 
    "virtualbox", "vagrant", "selenium", "unity", 
    "ros", "llvm", "fpga", "zookeeper", "cassandra", 
    "couchbase", "dynamodb", "memcached", "firebase", "supabase",
    "celery", "cron", "powershell", "bash", "zsh", "cmake", "makefile", 
    "bazel", "gradle", "maven", "ant", "junit", "pytest", "mocha", "jasmine", 
    "karma", "jest", "storybook", "webpack", "babel", "rollup", "parcel", 
    "tailwindcss", "bootstrap", "foundation", "material-ui",
    "bulma", "less", "sass", "electron", "capacitor", 
    "ionic", "cordova", "xamarin", "flutter",
    "hugging face transformers", "blockchain", "ethereum", "solidity", 
    "truffle", "hardhat", "wasm", "zeromq", "activemq", "consul", 
    "etcd", "saltstack", "puppet", "chef", "istio", "linkerd", "envoy", "grpc", 
    "thrift", "minio", "ceph", "glusterfs", "circleci",
    "bitbucket pipelines", "azure", "sentry", 
    "logstash", "fluentd", "loki", "jboss", 
    "tomcat", "websphere", "oracle", "db2", "sybase", "sqlite", 
    "clickhouse", "snowflake", "bigquery", "databricks",
    "plotly", "vega", "mapbox", "leaflet", 
    "cesium", "openlayers", "tensorrt", "onnx", "keras", "horovod", "mlflow", 
    "kubeflow", "tecton", "openshift", "cloudfoundry", "heroku", "netlify", 
    "vercel", "terraform cloud", "sonarqube", 
    "burp suite", "metasploit", "wireshark", "nmap", 
    "rundeck", "packer", "window", "ai", "rag", "llm", "ci", "cd",
    "gpt"
]

REPLACE_DICT = {
    "python": "파이썬",
    "ai": "인공지능",
    "java": "자바",
    "linux": "리눅스",
    "window": "윈도우",
    "javascript": "자바스크립트",
    "spring": "스프링",
    "react": "리액트",
    "docker": "도커",
    "kubernetes": "쿠버네티스",
    "tensorflow": "텐서플로우",
    "pytorch": "파이토치",
    "git": "깃",
    "github": "깃허브",
    "hadoop": "하둡",
    "unity": "유니티",
    "unreal": "언리얼",
    "nginx": "엔진엑스",
}